from PyQt5 import QtCore, QtGui, QtWidgets
from screeninfo import get_monitors
from PyQt5.QtCore import Qt


with open('pwd.txt', 'r') as pwd:
    path = pwd.read()

width = get_monitors()[0].width
height = get_monitors()[0].height

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Crystal")
        MainWindow.resize(width, height)
        MainWindow.setWindowFlag(Qt.FramelessWindowHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, width, height))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(f"{path}/img/UI/Desktop.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(width/2.3132530120481927, height/3, width/6.378737541528239, width/6.378737541528239))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(f"{path}/img/UI/Crystal new.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(width/5.64, height/12, width/4, height/3.5))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(f"{path}/img/UI/Detail.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(width/12, height/3, width/4, height/3.5))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(f"{path}/img/UI/Detail.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(width/5.33, height/1.7142857142857142, width/4, height/3.5))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(f"{path}/img/UI/Detail.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(width/(width/805), height/(height/130), width/(width/360), height/(height/250)))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/45)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent; color: darkgreen; border: none;")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(width/2.3132530120481927, height/3, width/6.378737541528239, height/3.711340206185567))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: white; background: transparent; border-radius: 145px;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(width/(width/800), height/(height/660), width/(width/390), height/(height/261)))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/54)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background: transparent; color: white; border: none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(width/(width/410), height/(height/170), width/(width/331), height/(height/60)))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/45)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowser_3.setStyleSheet("background: transparent; color: white; border: none;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(width/(width/410), height/(height/230), width/(width/331), height/(height/60)))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/45)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setStyleSheet("background: transparent; color: white; border: none;")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(width/1.71, height/18, width/2.7, height/2.24))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(f"{path}/img/UI/Details.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(width/1.71, height/2.20, width/2.7, height/2.24))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(f"{path}/img/UI/Details.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(width/1.5737704918032787, height/1.8305084745762712, width/3.7573385518590996, height/17.704918032786885))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(24)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(width/1.5737704918032787, height/6.75, width/3.7573385518590996, height/17.704918032786885))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(24)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: white;")
        self.label_10.setObjectName("label_10")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(width/(width/410), height/(height/290), width/(width/331), height/(height/60)))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/45)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setStyleSheet("background: transparent; color: white; border: none;")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(width/1.5238095238095237, height/4.5, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("background: transparent; color: white;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(width/1.5238095238095237, height/3.176470588235294, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setStyleSheet("background: transparent; color: white;")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(width/1.28, height/4.5, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("background: transparent; color: white;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(width/1.1851851851851851, height/3.176470588235294, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setStyleSheet("background: transparent; color: white;")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(width/1.391304347826087, height/4.5, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("background: transparent; color: white;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(width/1.1851851851851851, height/4.5, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setStyleSheet("background: transparent; color: white;")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(width/1.28, height/3.176470588235294, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_7.setStyleSheet("background: transparent; color: white;")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(width/1.391304347826087, height/3.176470588235294, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setStyleSheet("background: transparent; color: white;")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.weathericon = QtWidgets.QLabel(self.centralwidget)
        self.weathericon.setGeometry(QtCore.QRect(width/(width/300), height/(height/450), height/13, height/13))
        self.weathericon.setText("")
        self.weathericon.setScaledContents(True)
        self.weathericon.setObjectName("weathericon")
        self.temp = QtWidgets.QTextBrowser(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(width/(width/390), height/(height/460), height/7, height/10))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/30)
        self.temp.setFont(font)
        self.temp.setStyleSheet("background: transparent; color: white; border: none;")
        self.temp.setObjectName("temp")
        self.weathername = QtWidgets.QTextBrowser(self.centralwidget)
        self.weathername.setGeometry(QtCore.QRect(width/(width/390), height/(height/500), height/7, height/10))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/60)
        self.weathername.setFont(font)
        self.weathername.setStyleSheet("background: transparent; color: silver; border: none;")
        self.weathername.setObjectName("weathername")
        self.weatherdetails = QtWidgets.QTextBrowser(self.centralwidget)
        self.weatherdetails.setGeometry(QtCore.QRect(width/(width/330), height/(height/530), width/15, height/10))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/80)
        self.weatherdetails.setFont(font)
        self.weatherdetails.setStyleSheet("background: transparent; color: grey; border: none;")
        self.weatherdetails.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherdetails.setObjectName("weatherdetails")
        self.notificationbanner = QtWidgets.QLabel(self.centralwidget)
        self.notificationbanner.setGeometry(QtCore.QRect(width/(width/420), height/(height/730), height/3, height/7.2))
        self.notificationbanner.setText("")
        self.notificationbanner.setScaledContents(True)
        self.notificationbanner.setPixmap(QtGui.QPixmap(f"{path}/img/UI/glowing rect.jpg"))
        self.notificationbanner.setObjectName("notificationbanner")
        self.notificationnum = QtWidgets.QTextBrowser(self.centralwidget)
        self.notificationnum.setGeometry(QtCore.QRect(width/(width/420), height/(height/700), height/3, height/10))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/50)
        self.notificationnum.setFont(font)
        self.notificationnum.setText("9+ Notifications")
        self.notificationnum.setStyleSheet("background: transparent; color: white; border: none;")
        self.notificationnum.setAlignment(QtCore.Qt.AlignCenter)
        self.notificationnum.setObjectName("notificationnum")
        self.fromnotification = QtWidgets.QTextBrowser(self.centralwidget)
        self.fromnotification.setGeometry(QtCore.QRect(width/(width/440), height/(height/765), height/3.35, height/10))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/50)
        self.fromnotification.setFont(font)
        self.fromnotification.setText("Google")
        self.fromnotification.setStyleSheet("background: transparent; color: white; border: none;")
        self.fromnotification.setObjectName("fromnotification")
        self.notificationsubject = QtWidgets.QTextBrowser(self.centralwidget)
        self.notificationsubject.setGeometry(QtCore.QRect(width/(width/440), height/(height/790), height/3.35, height/10))
        self.fromnotification.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/80)
        self.notificationsubject.setFont(font)
        self.notificationsubject.setText("New Sign-in on a Linux Device\n\t\t\t\t\t        Please verify the device")
        self.notificationsubject.setStyleSheet("background: transparent; color: silver; border: none;")
        self.notificationsubject.setAlignment(QtCore.Qt.AlignCenter)
        self.notificationsubject.setObjectName("notificationsubject")
        self.notificationsubject.setAlignment(QtCore.Qt.AlignCenter)

        self.terminalOutput = QtWidgets.QTextBrowser(self.centralwidget)
        self.terminalOutput.setGeometry(QtCore.QRect(width/(width/1245), height/(height/690), height/2.3, height/8.1))
        font = QtGui.QFont()
        font.setPointSize(height/100)
        self.terminalOutput.setFont(font)
        self.terminalOutput.setText('Welcome to Plasma')
        self.terminalOutput.setStyleSheet("background: black; border-radius: 5px; color: white;")
        self.terminalOutput.setObjectName("terminalOutput")

        self.terminalDirectory = QtWidgets.QTextBrowser(self.centralwidget)
        self.terminalDirectory.setGeometry(QtCore.QRect(width/(width/1245), height/(height/660), height/2.3, height/35))
        font = QtGui.QFont()
        font.setPointSize(height/100)
        self.terminalDirectory.setFont(font)
        self.terminalDirectory.setText('Crystal@VatsalDutt:{0}$'.format(''))
        self.terminalDirectory.setStyleSheet("background: black; border-radius: 5px; color: #13b63e;")
        self.terminalDirectory.setObjectName("terminalDirectory")

        self.terminalCommand = QtWidgets.QLineEdit(self.centralwidget)
        self.terminalCommand.setGeometry(QtCore.QRect(width/(width/1370), height/(height/660), height/3.2, height/35))
        font = QtGui.QFont()
        font.setPointSize(height/100)
        self.terminalCommand.setFont(font)
        self.terminalCommand.setStyleSheet("background: black; border-radius: 5px; color: white; border: none;")
        self.terminalCommand.setObjectName("terminalCommand")

        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_3.raise_()
        self.textBrowser_4.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.textBrowser_5.raise_()
        self.pushButton_4.raise_()
        self.pushButton_9.raise_()
        self.pushButton_7.raise_()
        self.pushButton_5.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_6.raise_()
        self.pushButton_8.raise_()
        self.textBrowser_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser_3.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser_4.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser.raise_()
        self.weathericon.raise_()
        self.temp.raise_()
        self.weathername.raise_()
        self.weatherdetails.raise_()
        self.notificationbanner.raise_()
        self.notificationnum.raise_()
        self.fromnotification.raise_()
        self.notificationsubject.raise_()
        self.terminalOutput.raise_()
        self.terminalDirectory.raise_()
        self.terminalCommand.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Command Line Interface"))
        self.label_10.setText(_translate("MainWindow", "Desktop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

